defaultProject: nbalaji-477-20250527181051
defaultLocation: US
defaultDataset: dataform_extreme_weather_programming_example
defaultAssertionDataset: dataform_extreme_weather_programming_example_assertions
dataformCoreVersion: 3.0.0
"vars": {
    "ga4_action_dataset": "action_dataset",
    "ga4_export_dataset": "us_dataset"
    } 