defaultProject: nbalaji-477-20250527181051
defaultLocation: US
defaultDataset: dataform_extreme_weather_programming_example
defaultAssertionDataset: dataform_extreme_weather_programming_example_assertions
dataformCoreVersion: 3.0.0
"vars": {
    "weather_export_project": "preston-307021",
    "weather_action_dataset": "action_dataset",
    "weather_export_dataset": "us_dataset",
    "weather_export_table_suffix": "_v1",
    "start_date": "2023-01-01",
    "end_date": "2023-12-31",
    "output_table_partition_field": "event_date",
    "weather_data_lookback_days": "7"
    } 