config {
  type: "incremental", // Changed to incremental for pre_operations logic
  database: dataform.projectConfig.vars.weather_export_project,
  schema: constants.baseSchema("weather"),
  name: `${constants.FACT_TABLE_PREFIX}weather_line_items1`

}

js {
  const constants = require("includes/constants.js");
}

pre_operations {
  ${when(incremental(), `
    DELETE FROM ${self()}
    WHERE
      DATE(date) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL ${dataform.projectConfig.vars.weather_data_lookback_days} DAY)
      AND CURRENT_DATE();
  `)}
}

SELECT
    DATE_TRUNC(DATE(year, month, day), MONTH) AS date,
    COUNT(*) AS extreme_weather_count
FROM
    `bigquery-public-data.samples.gsod`
WHERE
    (
        snow = TRUE
        OR hail = TRUE
        OR thunder = TRUE
        OR tornado = TRUE
    ) -- The GitHub data only ranges from 2007 to 2012.
    -- The weather data is only available up to 2010.
    AND year >= 2007
GROUP BY
    date
ORDER BY
    date